### ISSUE TITLE
Consumer gets nothing in tests

### ISSUE THREAD

**Issue by fxn** [bbalser/elsa#59]
Not sure this is an issue or I am doing something wrong.

I am developing a Phoenix application that only produces messages:

```elixir
# lib/my_app/application.ex
{Elsa.Supervisor,
  endpoints: MyApp.Kafka.brokers(),
  connection: MyApp.Kafka.connection(),
  producer: Enum.map(MyApp.Kafka.topics(), &{:topic, &1})
}
```

The integration test suite for the endpoint that publishes those messages (a Phoenix Channel) sets a consumer up to verify them. This is the child spec:

```elixir
# test/test_helper.exs
def events_consumer_childspec(topic, state) do
  {Elsa.Supervisor,
    endpoints: MyApp.Kafka.brokers(),
    connection: :"my_app_test_#{topic}",
    consumer: [
      topic: topic,
      handler: __MODULE__.MessageHandler,
      begin_offset: :latest,
      handler_init_args: state
  ]}
end
```

The `setup` callback for the test launches the consumer this way:

```elixir
mhref = make_ref()
state = {self(), mhref}
start_supervised(events_consumer_childspec(topic, state))
```

The `mhref` is a reference used by the message handler to forward the messages back to the test process.

This setup is performed only for one test, the consumer is not created for any other test.

OK. The main test passes consistently alone, messages are published, consumed, and verified. Passes consistently with other tests that do not reach the code that publishes (eg, tests that hit a validation failure that prevents the code from reaching the producer).

Problem is, if a different test does publish a message before this main test runs, the message handler is never called, even waiting 1 min.

Is there anything wrong in that setup that explains this behavior off the top of your head?

Otherwise, I could try to get a minimal reproduction app using Docker Compose.

**Comment by jeffgrunewald** [comment]
Hey @fxn, can you help me understand the flow of information through your application?  Are you consuming messages off a Kafka topic and then publishing them via a Phoenix Channel, or reading messages off of a Phoenix Channel and producing them to a kafka topic?

**Comment by fxn** [comment]
The latter. This endpoint receives events sent by mobile clients to a channel, stores them in DynamoDB, and broadcasts them to the platform via Kafka. Pretty simple endpoint.

And that is all related to Kafka in the app except for a healthcheck endpoint that checks the existence of a certain topic (cheapest way I thought of checking we can talk to Kafka, please let me now if there is a better one!).

**Comment by jeffgrunewald** [comment]
Have you tried to reset the reset value to `:earliest`? With the `latest` policy, the consumer is joining the new group with no committed offset, so it will join and then technically consume the _next_ message on the topic to come in and commit an offset. If your tears ran in such a way that the message you’re waiting on was produced before the consumer was fully up and running I’m not sure that particular consumer will ever get that message

**Comment by fxn** [comment]
Let me show you the flow in the tests schematically:

```elixir
defmodule SomethingChannelTest do
  describe "scenario 1" do
    setup do
      # spawn consumer using the code in the issue description
    end

    test "stores event and publishes to Kafka" do
      # publish
      # assert I receive the expected payload from the consumer
    end
  end

  describe "scenario 2" do
    test "whatever" do
      # publish
    end
  end
end
```

Since there is no way to delete messages from a topic that I am aware of, the consumer configures `:latest` to ignore whatever is already in the topic and forward to the test process only what the test process produces. AFAICT, the workflow itself is correct.

Since there are several processes being created and dying in a test like this, I was wondering if Elsa could be managing something associated to a process like ETS tables or whatever that could be relevant.

If this does not make sense a priori, I'll try to reproduce in a minimal app.

**Comment by fxn** [comment]
Ah, to link with the description, is scenario 1 runs firts, the suite passes. It does not the other way around.

**Comment by jeffgrunewald** [comment]
We found trying to assert reliably against a kafka instance that doesn’t have a clean state between test runs was too burdensome to work with and my gut tells me that your problem is rooted in not being able to guarantee the state of the topic on every run of the test. 

For that reason, we do all of our testing against a single-node kafka running in docker (Elsa orchestrates this with a hex library called divo) and point our tests to the endpoint `[localhost: 9092]`. Barring that, I would try to create and tear down topics dynamically on a per-test basis. If nothing else, that should rule out my theory as the source of your problem.

**Comment by fxn** [comment]
Cool, so that tells me in principle the way I create a consumer in the `setup` callback looks correct. That is alredy helpful.

I'll see what happens if I recreate the topic between tests.

**Comment by jeffgrunewald** [comment]
Yeah, whether or not you do it in a setup callback, I believe you want to ensure your consumer is running before calling `produce`

**Comment by fxn** [comment]
> I believe you want to ensure your consumer is running before calling produce

Yes, I am sure that is the case. The tests run one after the other, and setup runs synchronously before its test.

**Comment by fxn** [comment]
I have gotten a [minimal Phoenix application that reproduces the issue](https://github.com/fxn/elsa_issue) and does not use channels.

Installation:

```
git clone https://github.com/fxn/elsa_issue.git
cd elsa_issue
docker-compose up -d
dc/mix deps.get
dc/mix compile
```

Overview:

* [`docker-compose.yml`](https://github.com/fxn/elsa_issue/blob/master/docker-compose.yml) includes Kafka and it is configured such that `up` creates a topic called "elsa-issue".
* The [application callback module](https://github.com/fxn/elsa_issue/blob/master/lib/elsa_issue/application.ex) defines a producer for that topic.
* The `index` action of [this dummy controller](https://github.com/fxn/elsa_issue/blob/master/lib/elsa_issue_web/controllers/hello_controller.ex) publishes the current time to that topic every time it is called.

You can check everything is good by launching the server:

```
dc/mix phx.server
```

a command-line Kafka consumer:

```
dc/consume
```

and doing requests to that endpoint:

```
curl http://localhost:4000/api
```

The consumer console will show traces like

```
2020-02-03 19:19:05.204887Z
2020-02-03 19:19:05.370378Z
2020-02-03 19:19:18.955209Z
2020-02-03 19:19:19.364575Z
2020-02-03 19:19:27.936118Z
...
```

* The test suite [defines](https://github.com/fxn/elsa_issue/blob/master/test/test_helper.exs) a childspec and a message handler for a consumer that listens to the "elsa-issue" topic.

* The [test suite for that controller](https://github.com/fxn/elsa_issue/blob/master/test/elsa_issue_web/controllers/hello_controller_test.exs) has one test that produces and consumes, and another test that only produces. In the former, it is clear that the consumer is created before the test calls the action, which is what produces.

OK, if the first test runs first:

```
dc/mix test --seed 927034
```

the suite passes.

But if the first test runs second:

```
dc/mix test --seed 578823
```

the message handler does not get called in test 1.

This behavior does not seem to be correct, right?

**Comment by fxn** [comment]
BTW, reproduction steps use tests, but I do not mean this is related to tests in particular, perhaps it is related to having several processes alive and killed, and two Elsa supervisors involved, or something like that.

**Comment by jeffgrunewald** [comment]
Thanks for the sample repo and setup instructions; it made debugging the issue really simple.

It looks like the problem you're seeing is a timing issue; since the consumer worker is subscribing to the topic in a `handle_continue/2` instead of its `init/1` block, you're still producing before the worker has finished starting up and subscribing and since your strategy is set to `:latest`, the message has already passed by the time the consumer is listening for it. _Strictly to make the test pass_, adding a `Process.sleep(1000)` anywhere between starting the consumer and calling `produce` solves the problem.

If _all_ you're looking to do is confirm reliability of the producer and consumer, and you're comfortable with a sleep in your test, that should solve the problem. If you're concerned about missing a message at the beginning of consuming though, we're open to suggestions on how to address the problem.

As a general rule, we've tried to avoid putting network calls to Kafka into `init` functions to make the overall Elsa supervision strategy more stable and resilient so moving the location of the subscribe doesn't feel like a great option.

Another option if you're really just looking to validate reliability of your app producing to Kafka and you're reusing an existing topic (meaning an `:earliest` strategy won't work) you might also consider including some identifying factor in your message key or value and then using the `Elsa.search/4` or other `Elsa.search_*/4` functions to query the topic to validate your test message was successfully written to the topic.

Thoughts?

**Comment by fxn** [comment]
Ahhh, understood.

This is for black box testing purposes only, so I will be able to workaround it with your suggestions. In my particular use case, it would be nice to be able to block until the consumer is ready, but whether that deserves API in Elsa is something you are in a better position to assess.

Thanks a lot for looking into this so quickly!

**Comment by fxn** [comment]
@jeffgrunewald what does explain that the problem depended on the order of execution of the tests? Test 1 is the one with the race condition, creating the consumer and producing right after it, and it consistently passes if it runs first (or if it is the only test in the suite).

If test 2 runs first, and test 1 second, test 1 consistently fails (the handler is not called). Is the message produced by test 2 influencing the time it takes for the consumer to be ready ?

**Comment by jeffgrunewald** [comment]
We're not entirely sure but my guess is that the previous interaction with the cluster from test 2 running first causes the connection time for the consumer in test 1 to take longer, like a rebalance. That in and of itself doesn't seem like the answer since rebalances should only occur on subsequent connections to the same _consumer group_, not the same topic, but something to that effect feels like the answer to me.

**Comment by fxn** [comment]
OK, thanks!

I am thinking about rewriting this test with the search functions. It would be optimal to use `start_offset`. How is this option interpreted when there are several partitions in the topic? Is there a way to query the current offset before the test runs to then search from there? Did not find anything in the API but perharps I missed it.

**Comment by jeffgrunewald** [comment]
that option will be used as the starting and ending point for a search across all partitions, so for instance if you limit your offset range to `start_offset: 10, end_offset: 20` then that range will be searched across any partitions on the topic (if you're using the `fetch_stream` or `search*` functions.

We didn't add any API to query the offsets across all partitions on a topic but it would be easy to do so by iterating over the partitions on the topic and calling `:brod.resolve_offset(endpoints, topic, partition, offset)` where the offset can be any of `:earliest | :latest | integer()`
