### ISSUE TITLE
{:no_ack, _} and {:ack, offset, _} are broken

### ISSUE THREAD

**Issue by jtrees** [bbalser/elsa#96]
I've been trying to figure out how nacking works and have come to the conclusion that their current implementation is broken.

Here are some scenarios that demonstrate how messages are routed in the status quo and how that differs from my expectations. They describe the view of a single message handler.

#### Status Quo
1. `handle_messages/2` is called with a single message: [offset: 42].
2. The function returns `{:no_ack, :foo}`.
3. `handle_messages/2` is called with a single message: [offset: 43].

#### Expected Behaviour
Step 3 should look more like one of the following:
1. `handle_messages/2` is called with a single message: [offset: 42] (the same message from Step 1 above)
2. `handle_messages/2` is called with two messages: [offset: 42, offset: 43] (the same messages from Step 1  and Step 3 above)

#### Status Quo
1. `handle_messages/2` is called with three messages: [offset: 42, offset: 43, offset: 44]
2. The function returns `{:ack, 43, :foo}`.
3. `handle_messages/2` is called with a single message: [offset: 45]

#### Expected Behaviour
Step 3 should look more like the following:
1. `handle_messages/2` is called with two messages: [offset: 43, offset: 44]
2. `handle_messages/2` is called with three messages [offset: 43, offset: 44, offset: 45]

#### Status Quo
1. `handle_messages/2` is called with a single message: [offset: 42].
2. The function returns `{:no_ack, :foo}`.
3. `handle_messages/2` is called with a single message: [offset: 43].
4. The app crashes.
5. The app is brought back up.
6. `handle_messages/2` is called with a single message: [offset: 42].

#### Expected Behaviour
Exactly this. Hooray!

### Scenario 4

This one is particularly dangerous, and would automatically be redundant if Scenario 1 and 2 get fixed.

#### Status Quo
1. `handle_messages/2` is called with one message: [offset: 42]
1. The function returns `{:no_ack, :foo}`.
1. `handle_messages/2` is called with one message: [offset: 43]
1. The function returns `{:ack, :foo}`.
1. `handle_messages/2` is called with a single message: [offset: 44]
1. The app crashes.
1. The app is brought back up.
1. `handle_messages/2` is called with a single message: [offset: 44].

#### Expected Behaviour
After bringing the app back up the handler should continue at offset 42. The ack we sent in Step 4 was not intended for the message with offset 42. We didn't even see it when the function was called that returned the ack!

## Additional Comments

For now it might be able to work around the inconsistent behaviour by deliberately triggering a handler crash after nacking a message so we end up in something like Scenario 3. That's a pretty ugly workaround though.

**Comment by mhanberg** [comment]
I think we have also run into this.

**Comment by GregMefford** [comment]
This is just a guess, but I'm thinking that maybe the issue is that when you nack or partially-ack a batch of messages, you are telling `brod` the right thing to ack in terms of Kafka, but [this GenServer is asynchonously receiving batches](https://github.com/bbalser/elsa/blob/master/lib/elsa/consumer/worker.ex#L104) of messages from `brod`, so it might already have one or more subsequent batches queued up for you, which would be bad if you consumed and acked them, entirely skipping over the ones that you nacked or partially-acked.

I'm not sure how to handle that exactly, but I feel like you need some way to communicate to `brod` that it should re-fetch starting from whatever you nacked or  partially-acked, and then purge or invalidate any queued-up messages inside Elsa (in the mailbox, in GenServer state, etc.) so that you won't get another message until `brod` re-fetches a batch. Maybe there's some room for optimization there if Elsa maintained its own queue and such, since there's actually no reason to re-fetch what you already have, though. 🤔

**Comment by jeffgrunewald** [comment]
Sorry for the long delayed response, especially since I believe there may just be some confusion about how offset-based asking in Kafka works.

Looking at the difference scenarios defined in the OP this is exactly the behavior I would expect from a Kafka consumer operating successfully. This is because Kafka consumers take into account not 1 but 2 different offsets: the _committed_ offset and the _consumed_ offset. Whether you've responded with an `ack` or a `no_ack` the _consumed_ offset is incremented which is why you should expect the offset to continue to increment even when you're responding with `no_ack`. However, in the event of an app crash the consumer which has been tracking the _consumed_ offset is down and has to resubscribe to the topic, which is when it starts counting again from the _committed_ offset (the last offset that was `ack` ed). And, since Kafka specifically operates on offset-based acking, all offsets prior to an `ack` ed offset are assumed to be `ack` ed as well.

This [stack overflow](https://stackoverflow.com/questions/64461894/kafka-offset-increments-even-without-reaching-ack) article described it well I believe.

So for example, in scenario 1 when you receive offset 42 and then `no_ack` and then receive offset 43 next this is to be expected b/c the consumer has incremented the consumed offset (I consumed offset 42 and asked for more messages by calling `handle_messages/2`)

In scenario 2 you've received (and consumed) offsets 42-44 and `ack` ed offset 43. Then you receive offset 45, but since you _haven't_ described an app crash, the consumer's consumed offset has continued to count the most recently consumed offset, which is 44, meaning 45 is next.

In scenario 3 you've consumed offset 42 and moved onto offset 43, but then you've crashed so the app comes back up and the consumer re-subscribes, rolling you back to offset 42 (frankly this would be surprising to me since you `no_ack` ed offset 42 so I would _expect_ you to start back even further.

Finally in scenario 4 you've consumed offsets 42 and 43 and `ack` ed at offset 43. Since you didn't specify which offset to ack, it implicitly acks the most recently consumed offset (43). Then you attempt to consume offset 44 and the app crashes. When it comes back up and the consumer re-subscribes it picks up with offset 44 since you previously `ack` ed at offset 43 and by doing so `ack` ed all previous offsets.

These are a lot of the reasons why Kafka enjoys such fast performance over alternatives like Rabbit and Pulsar which support individual message `ack` ing; by only `ack` periodically you avoid the network overhead of going back to the kafka brokers to register a committed `ack` and only track the most recently consumed offsets locally by the consumer (the consumed offset). Similarly, offset-based `ack` ing means you implicitly `ack` all consumed messages from a single point instead of having to send commit `ack` s back to the brokers 1-for-1.

Hope that helps!

**Comment by jtrees** [comment]
Thanks for the detailed reply. Seems I misunderstood how Kafka works.

Guess this can be closed now. Thanks again.
